### PR TITLE
Add class and line number to warning about unknown section

### LINKED ISSUE #99: Unknown Section error has no context.
Similar to #95 the "Unknown section: X" error has no context, making it really hard to find and fix :-/

### PR DESCRIPTION
**Pull request by amueller**
Fixes #99

### CODE REVIEW

**Comment by amueller** [comment]
It looks like right now it raises multiple warnings for each occurrence (for sklearn) but the test only shows one warning... hm...

**Comment by jnothman** [comment]
I've not checked this in the case of the current patch, but one thing to be careful with is that the object that a docstring applies to is not necessarily in the same file as where the docstring is defined. Apart from directly setting `__doc__` to some variable from elsewhere (which doesn't happen in scikit-learn, but does in Pandas and, I think, Numpy), this happens often through inheritance.

Btw, @amueller, you may be interested in https://github.com/jnothman/numpydoc/commit/1d21eb1ff84f15cfbb4e5114f4823262d105996d where I get line offsets within a docstring for parameter entries. I just haven't quite pulled this together into something useful yet :|

**Comment by amueller** [comment]
Hmm yeah good point.
But I'm a fan of iterative solutions ;)
This one is helpful in many cases, but not all.

Inheritance might be a reason why I get multiple warnings in sklearn.
I'll check out your commit. Last time I checked the munging made it really
hard to get corresponding lines. I was thinking that displaying the
offending line might be easier.

Sent from phone. Please excuse spelling and brevity.


On Jul 19, 2017 20:03, "Joel Nothman" <notifications@github.com> wrote:

I've not checked this in the case of the current patch, but one thing to be
careful with is that the object that a docstring applies to is not
necessarily in the same file as where the docstring is defined. Apart from
directly setting __doc__ to some variable from elsewhere (which doesn't
happen in scikit-learn, but does in Pandas and, I think, Numpy), this
happens often through inheritance.

Btw, @amueller <https://github.com/amueller>, you may be interested in
jnothman/numpydoc@1d21eb1
<https://github.com/jnothman/numpydoc/commit/1d21eb1ff84f15cfbb4e5114f4823262d105996d>
where I get line offsets within a docstring for parameter entries. I just
haven't quite pulled this together into something useful yet :|

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/numpy/numpydoc/pull/101#issuecomment-316556859>, or mute
the thread

**Comment by stefanv** [comment]
I ran into this exact error recently: it said "error in None from None", or something like that.  So, I'm all for iterative improvement.

**Comment by jnothman** [comment]
Don't get me wrong, I'm all for this change.

**Comment by rgommers** [comment]
+1 helpful indeed. Doesn't work for everything but does for plain Python code at least. Just tried it on SciPy and got a couple of each of these:

    /Users/rgommers/Library/Python/3.5/lib/python/site-packages/numpydoc/docscrape.py:360: 
    UserWarning: Unknown section Exampes in the docstring of None in None.
      warn(msg)
    /Users/rgommers/Library/Python/3.5/lib/python/site-packages/numpydoc/docscrape.py:360: 
    UserWarning: Unknown section Parameers in the docstring of <function periodogram at 0x10ac9e840> in /Users/rgommers/Code/scipy/scipy/signal/spectral.py.
      warn(msg)

**Comment by rgommers** [comment]
@amueller not sure if you wanted to check out that commit of @jnothman for this PR, but I'd be happy to merge this now.

**Comment by rgommers** [comment]
@jnothman and @amueller looks like you are both up to speed with the numpydoc internals and have an interest in the package. Do you want commit rights?

**Comment by amueller** [comment]
@rgommers Maybe I should remove the "of None in None"? But I guess that's details.
Happy to have this merged now, or I can detect "None".
And I'd take commit rights, but I can't promise I'll review anything. I'm a couple hundred reviews behind on sklearn ;)

**Comment by stefanv** [comment]
Yes, please spread the commit rights to numpydoc!  Thanks for taking initiative, Ralph.

**Comment by rgommers** [comment]
> Maybe I should remove the "of None in None"? But I guess that's details.

Yeah that doesn't bother me, removing it won't locating the offending line easier.

> And I'd take commit rights, but I can't promise I'll review anything. I'm a couple hundred reviews behind on sklearn ;)

Excellent, team made and https://github.com/orgs/numpy/teams/numpydoc-devs sent. And yeah, totally understand about no commitments. I suspect we're all in the same boat here:)

**Comment by jnothman** [comment]
Merge?

**Comment by amueller** [comment]
I think consensus was merge and we iterate?

**Comment by amueller** [comment]
@jnothman you should have merge rights, right? (I can't but maybe there is a "can't merge own PRs setting?")

**Comment by jnothman** [comment]
Why should I?

**Comment by amueller** [comment]
Oh I thought @rgommers gave us rights, but maybe not?

**Comment by rgommers** [comment]
> Oh I thought @rgommers gave us rights, but maybe not?

I asked both of you, and you said yes. @jnothman didn't respond so I didn't give him the rights. Very happy to do so now though. Do you want them @jnothman?

**Comment by jnothman** [comment]
I'm happy to have rights. Thanks

**Comment by rgommers** [comment]
Awesome! Invite sent.

**Comment by amueller** [comment]
thanks :)

**Pull request merged**
