### PR TITLE
Fix clean_backref for extensions that have backrefs to inline elements.

### PR DESCRIPTION
**Pull request by mcmtroffaes**
Originally reported here:

https://github.com/mcmtroffaes/sphinxcontrib-bibtex/issues/277

### CODE REVIEW

**Review by larsoner — COMMENTED** [review]
Seems reasonable to me. Ideally it would be nice if we could add a test that fails on `main` and passes on this PR -- @mcmtroffaes how difficult do you think this would be?

**Comment by mcmtroffaes** [comment]
Thanks for the quick response. Yes, I think I should be able to add a test.

**Comment by mcmtroffaes** [comment]
I've added a test.

**Review by rossbar — APPROVED** [review]
LGTM, thanks @mcmtroffaes !

**Comment by mcmtroffaes** [comment]
Awesome, many thanks for merging!

**Pull request merged**
