### PR TITLE
Use black

### PR DESCRIPTION
**Pull request by jarrodmillman**
I am leaving this draft until it is approved to prevent it from being merged. If it is approved, I will merge it (but not squash it, so I will need to enable that option before merging). The reason I will do that is so I can keep all the black formatting stuff in one commit that I will add to a `.git-blame-ignore-revs` file.

### CODE REVIEW

**Comment by larsoner** [comment]
I have not kept up to speed on what NumPy has done, but +1 for merge assuming this follows whatever they do, whenever they do it :)

**Review by larsoner — APPROVED** [review]
I'll approve but it would be nice if another maintainer (@rgommers ? @jnothman ?) could weigh in as well!

**Review by stefanv — APPROVED** [review]

**Review by rossbar — APPROVED** [review]
I'm +1 on adding an autoformatter as well. Given the discussion on the numpy mailing list, black seems like the sensible choice. Some of the other concerns for numpy e.g. the formatting for math and large arrays are not really a concern for numpydoc.

**Comment by larsoner** [comment]
Okay sounds like you have the green light to proceed @jarrodmillman !

**Pull request merged**
