### PR TITLE
Added ..currentmodule:: before ..autosummary::

### PR DESCRIPTION
**Pull request by SirNO**
This addition solves an issue I had with the method section generated by numpydoc

### CODE REVIEW

**Comment by SirNO** [comment]
this resolves #80

**Comment by stefanv** [comment]
Can anyone else confirm this issue?

**Comment by rgommers** [comment]
I've confirmed that this fixes the example given in gh-80 (which looks like a valid way to use ``autoclass``) and that it doesn't cause any problems for the scipy doc build. So merging.

Thanks @SirNO

**Comment by rgommers** [comment]
Hmm, this passed its tests earlier but is now broken after merging says TravisCI. Will investigate.

**Comment by rgommers** [comment]
Fix in gh-86. @SirNO can you please double check that?

**Pull request merged**
