### PR TITLE
Use DEDUPLICATION_TAG to determine whether a citation node is in a docstring

### LINKED ISSUE #177: References messed up
Version 0.8.0 of numpydoc supposedly fixed the referencing issue, but in my case it got worse, and I wonder why (related to #114).

---

With `numpydoc v0.6.0` I get the following:

So for instance [Key_2012]: author_year, exactly what I intended to do.

---

With `numpydoc v0.7.0` I get the following:

So it added a '0' to each reference.

---

But now with `numpydoc v0.8.0` I get the following:

I assume that is not as was intended with the bugfix in #136?

---

Should I change the way I use references, or is this a bug that persists in numpydoc?

I have in readthedocs numpydoc fixed to 0.6.0, but if it helps the complete manual is here: http://empymod.readthedocs.io

Details regarding the build using conda (and pip for sphinxcontrib-napoleon) with Python 3.6:

`numpydoc v0.8.0` and `numpydoc v0.7.0`:
sphinx 1.7.4; sphinxcontrib 1.0; sphinxcontrib-napoleon 0.6.1.

`numpydoc v0.6.0`
sphinx 1.6.6; sphinxcontrib 1.0; sphinxcontrib-napoleon 0.6.1.

### PR DESCRIPTION
**Pull request by jnothman**
Fixes #177

This should handle the case of a module docstring when relabelling munged reference labels.

This probably deserves a non-regression test.

### CODE REVIEW

**Comment by jnothman** [comment]
@prisae says this works for him, which is a good start!

**Comment by prisae** [comment]
Thanks @jnothman, would indeed have been better to state it here.

**Comment by prisae** [comment]
Hi @jnothman. Do you know if there is any new release planned in the near future (so these changes would be available, for instance, in readthedocs.org)?

**Comment by jnothman** [comment]
Sorry, I've not given this project much attention (along with several others I have not had time to give to). This would need to be reviewed by other contributors and merged before release.

**Comment by rgommers** [comment]
I don't have plans for a release in the near future, sorry, too many other balls to juggle at the moment. Unless something breaks or gets fixed that ups the priority.

**Comment by prisae** [comment]
Thanks @jnothman and @rgommers . No problem, just thought I'd ask. Might do it again in a couple of months... :wink:

**Comment by jnothman** [comment]
This has been road tested as noted above.

**Comment by prisae** [comment]
Yes, I can use it locally without issues. However, if it is released it would be possible to use it, e.g., on readthedocs.io etc. (There are probably workarounds to install directly from GitHub instead of pypi on readthedocs and friends.)

**Comment by larsoner** [comment]
@jnothman is it easy enough to add a regression test? If not perhaps we can live with the user tests here

**Comment by larsoner** [comment]
> There are probably workarounds to install directly from GitHub instead of pypi on readthedocs and friends

`pip` will accept things like:
```
$ pip install https://api.github.com/repos/numpy/numpydoc/zipball/master
```
And such entries can live in `requirements.txt` files

**Comment by prisae** [comment]
Thanks @larsoner, will give that a try!

**Comment by rgommers** [comment]
Looks like we should merge this for the next release, even without a test.

@jnothman agree? can you rebase?

**Comment by jnothman** [comment]
Happy to do the rebase. I haven't reassessed how easily it can be tested.

**Comment by larsoner** [comment]
Works fine for me on MNE and SciPy docs, but neither of those showed the problem.

@prisae can you test this PR to see if it fixes your problem?

**Comment by prisae** [comment]
I did, and it works fine for me (https://github.com/numpy/numpydoc/issues/177#issuecomment-400668997). Locally I am using it since @jnothman published it, without issues.

**Comment by larsoner** [comment]
Okay let's merge for now then since it seems to work, not break anything, and @rgommers is happy (and so am I). Thanks @jnothman

**Comment by prisae** [comment]
Great, happy to have that in, thanks everyone!

**Pull request merged**
