### PR TITLE
DOC: Added example of multi-line code in Examples section.

### PR DESCRIPTION
**Pull request by pvanmulbregt**
Moving a PR from numpy (numpy/numpy#10880) to numpydoc.
Adds an example of code spanning multiple lines.

### CODE REVIEW

**Comment by pvanmulbregt** [comment]
Can you be a bit more explicit?  "Multi-line code" and "within-block comments" seem different to me.  Are you saying combine them in some way?  Or remove the within-block-comments?

**Comment by mattip** [comment]
@jnothman ping - what is the "previous code chunk" to be removed?

**Comment by jnothman** [comment]
This is okay as is

**Comment by jnothman** [comment]
Thanks

**Pull request merged**
