### PR TITLE
Use definition lists rather than blockquotes

### PR DESCRIPTION
**Pull request by jnothman**
This probably falls under the category of "if it ain't broke, don't fix it", but I note that we're strangely using blockquotes for parameter listings instead of definition lists. UPDATED: now this PR proposes to use definition lists by default, with a switch to use the legacy blockquotes.

From [RST docs](http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#definition-lists):

> A definition is a block indented relative to the term, and may contain multiple paragraphs and other body elements. **There may be no blank line between a term line and a definition block (this distinguishes definition lists from block quotes).**

(emphasis mine)

As shown in the screenshots below, there are formatting differences in the default stylesheets:
* definition lists have more semantic HTML markup
* parameter names are bolded in definition lists; we currently mark them up explicitly in numpydoc
* type specs fill the place of classifiers in the RST spec, and are formatted with bold and italics
    * the `:` has the class `classifier-delimiter` and what follows has the class `classifier`
* the definition (i.e. parameter description) has smaller margins on all sides, meaning the parameter listing is much more compact, and the description has more visual affinity with the parameter it describes.

definition lists (with this patch):
definition lists (with this patch)

blockquotes (at master)
blockquotes (at master)

Does anyone know of disadvantages to definition lists, or why they have not been used here?

This patch should probably be extended to ensure that the first line of a parameter description is *not* blank, or it will revert to the blockquote styling.

This also highlights a problem with numpydoc's tests: vertical whitespace is significant in RST, particularly its presence/absence, but tests currently ignore blank lines, which is a Bad Idea.

### CODE REVIEW

**Comment by pv** [comment]
Such change may mess up existing stylesheets that assume something about the generated html.

**Comment by jnothman** [comment]
I'm aware, and so I'm inclined to raise this issue and close the PR. But what we do currently is pretty weird.

**Comment by jnothman** [comment]
FWIW, the background to my concern here is about trying to style the definition list... only to discover that we're not using a definition list, hence the term has no distinguishing markup around it.

**Comment by pv** [comment]
The code is soon 10 years old, so if I wrote it I don't remember the reason for this any more.
If a reason is not obvious, it may well be there's no reason...

**Comment by jnothman** [comment]
yes, I suspect it's accidental or to handle some case where people were
putting blank lines between param name and description in the docstring.

sigh. I suppose we will hack solutions on the client side or none at all

**Comment by stefanv** [comment]
Or, fix it to be consistent, and wait for complaints to pop up?

**Comment by jnothman** [comment]
Well, there's no problem of internal inconsistency... it's just a weird use of RST.

**Comment by jnothman** [comment]
I've pushed a change which uses definition lists by default but allows users requiring the legacy styling to switch this on with a config option to be removed in release 0.10. WDYT?

I've also changed the tests to be sensitive to the presence or absence of blank lines, but to ignore multiple (and those at the beginning or end), when comparing rendered and expected reST. Presence and absence of single blank lines is (very) significant in reST!

**Comment by pv** [comment]
TBH, I would just make the change, maybe break stuff, and wait for complaints.

rebase needed.

**Comment by jnothman** [comment]
I don't see the harm in keeping an alternative, though. Is it worth the
effort of changing it back to not have an option?

**Comment by pv** [comment]
No harm in having an option --- I didn't see before commenting that you had already implemented the option.

**Pull request merged**
