### PR TITLE
Use setuptools

### PR DESCRIPTION
**Pull request by jarrodmillman**
distutils is deprecated

### CODE REVIEW

**Review by rgommers — COMMENTED** [review]
Thanks Jarrod. Did you check that the files included in the sdist didn't change? That's the main concern here.

**Comment by jarrodmillman** [comment]
Yes, it looks like the files didn't change (except with minor differences).

Here's how I checked:

```
git checkout main  # b5b7e25
git clean -fxd
python setup.py sdist
mkdir ../test-distutils
cd ../test-distutils
tar xvzf ../numpydoc/dist/numpydoc-1.2.dev0.tar.gz
cd ../numpydoc

git checkout setuptools  # c75a655
git clean -fxd
python setup.py sdist
mkdir ../test-setuptools
cd  ../test-setuptools
tar xvzf ../numpydoc/dist/numpydoc-1.2.dev0.tar.gz

cd ..
```

Then I compared them
```
$ diff -r test-distutils test-setuptools
Only in test-setuptools/numpydoc-1.2.dev0: numpydoc.egg-info
diff -r test-distutils/numpydoc-1.2.dev0/setup.cfg test-setuptools/numpydoc-1.2.dev0/setup.cfg
2,4c2,4
< addopts =
<     --showlocals --doctest-modules -ra --cov-report= --cov=numpydoc
<     --junit-xml=junit-results.xml --ignore=doc/
---
> addopts =
> 	--showlocals --doctest-modules -ra --cov-report= --cov=numpydoc
> 	--junit-xml=junit-results.xml --ignore=doc/
6,9c6,14
< filterwarnings =
<     ignore:'U' mode is deprecated:DeprecationWarning
<     ignore:.*sphinx\.util\.smartypants is deprecated.*:
<     ignore:Using or importing the ABCs.*:DeprecationWarning
---
> filterwarnings =
> 	ignore:'U' mode is deprecated:DeprecationWarning
> 	ignore:.*sphinx\.util\.smartypants is deprecated.*:
> 	ignore:Using or importing the ABCs.*:DeprecationWarning
>
> [egg_info]
> tag_build =
> tag_date = 0
>
diff -r test-distutils/numpydoc-1.2.dev0/setup.py test-setuptools/numpydoc-1.2.dev0/setup.py
4,6c4
< import setuptools  # may monkeypatch distutils in some versions. # noqa
< from distutils.command.sdist import sdist
< from distutils.core import setup
---
> from setuptools import setup
64d61
<     cmdclass={"sdist": sdist},
```

Here are the differences:

1. The setuptools only includes `numpydoc.egg-info`.

```
$ ls test-setuptools/numpydoc-1.2.dev0/numpydoc.egg-info/
dependency_links.txt  PKG-INFO  requires.txt  SOURCES.txt  top_level.txt
```

2. The setuptools only adds extra space to the `setup.cfg` and appends this to the end of the file:

```
[egg_info]
tag_build =
tag_date = 0
```

3.  The setuptools only has the expected changes in `setup.py`.

**Comment by jarrodmillman** [comment]
Rebased on main.

**Review by rossbar — APPROVED** [review]
Those changes look fine to me, thanks @jarrodmillman

**Comment by immense055** [comment]
jarrodmillman:setuptools

**Pull request merged**
