### PR TITLE
Expose extension version

### PR DESCRIPTION
**Pull request by jschueller**
supercedes #51

### CODE REVIEW

**Comment by amueller** [comment]
Why is a separate file better than ``__init__.py``? (sorry if that's a stupid question)

**Comment by jschueller** [comment]
@amueller that way I can import only the version

**Comment by amueller** [comment]
Can you give an example? If you do ``from numpydoc._version import __version__`` Python will still read the ``__init__.py`` file, right?

**Comment by jschueller** [comment]
How would you do it ?

**Comment by pv** [comment]
I don't think there is a reasonable way to do it.

The handling of the release version is also somewhat suspect currently --- it should be `0.7.0.dev0` during development, and switched to `0.7.0` only in the release commit.

**Comment by amueller** [comment]
@pv do you want to change it to 0.7.0.dev0? that would be helpful I think.

**Comment by callegar** [comment]
@amueller Having a dedicated file has several advantages, because you can have _only_ the version number in it. In turn, this means that:

1.  you can easily read the version without executing the file (or by executing a file that you know that certainly has no side effect). This means that you can safely read the version number from setup.py. Conversely, having the version number in the package __init__.py means that this cannot generally be safely read from setup.py, because at the time setup.py is invoked, the package will not yet be installed and __init__.py may not be able to complete without errors, or another version of the package might be installed.
2. you can easily update the version number programmatically (e.g. from the tags of a version control system, such as git)

@pv I suggest that the project should eventually move to read the version directly from the vcs (e.g. using the versioneer package)

**Comment by rgommers** [comment]
> I don't think there is a reasonable way to do it.

Reading in a separate file and parsing as text rather than importing doesn't sound completely unreasonable.

**Comment by jnothman** [comment]
Can't we do this sort of think but make numpydoc.setup import numpydoc.numpydoc.setup locally?

**Pull request closed without merging**
